### ISSUE TITLE
Possible clarifications to README.rst

### ISSUE THREAD

**Issue by dg1727** [dano/aioprocessing#1]
I'm interested in synchronization objects like `Lock` that work both with `asyncio` and with the `threading` module.  It looks like `aioprocessing` is meant to provide such.  

It seems to me that the synchronization objects in the Python `threading` module should **not** be used from multiple `asyncio` coroutines.  For example, if a single-threaded `asyncio` program calls .acquire() on a `threading.Lock` that is held by another re-entrant copy of the same coroutine, then the program will hang because the `threading` .acquire() won't allow execution to switch to the other coroutine copy, in the same thread, that would release the lock.  

A.  Does it seem to be a fair assumption that, likewise, the `asyncio` synchronization objects (https://docs.python.org/3/library/asyncio-sync.html) may not be safe to use from multiple `threading` threads, so that the `aioprocessing` synchronization objects can be considered in these situations?  Your existing README.rst presents `aioprocessing` as an alternative to the `multiprocessing` synchronization objects, but not as an alternative to the `threading` ones.  You might want to update README.rst on this point.  

Or if the standard `asyncio` synchronization objects **are** thread-safe, I would be interested in a reference to somewhere on the Web that states this, and you might also mention this in README.rst so potential users will know they don't have to use `aioprocessing` for multithreaded, single-process asyncio programs.  

B.  Can you mention briefly in README.rst what are 
> the normal risks you get when you mix threads with fork()

?  I checked the Web for material on this but didn't find any.  

Thanks for your attention.

**Comment by dano** [comment]
> It seems to me that the synchronization objects in the Python threading module should not be used from multiple asyncio coroutines.

Correct.

> Does it seem to be a fair assumption that, likewise, the asyncio synchronization objects may not be safe to use from multiple threading threads?

Also correct. The `asyncio` documentation actually explicitly states this in the description of  every synchronization object.

And yes, the `aioprocessing` synchronization objects can be used in a multi-threaded program that also uses `asyncio` coroutines, because `aioprocessing` will avoid blocking the event loop when it tries to acquire the `multiprocessing.Lock`. It does this by acquiring the underlying `multiprocessing.Lock` in a background thread, whenever `coro_acquire` is called. `asyncio` has a mechanism (`BaseEventLoop.run_in_executor`) for waiting on a function to complete in a background thread without blocking in the event loop, so `aioprocessing` leverages that to do the  `multiprocessing.Lock.acquire` call. It will also do the right thing when `release` is called (release in the background thread, or release in the current thread, depending on if `coro_acquire` or `acquire` was called).

I'll add a note in the README pointing this out.

The thread/fork() mixing danger is that some thread will hold a lock at the moment you fork your child, and then your child will want to acquire that lock. Because the lock will only get released in the parent, your child will deadlock. See here for an example of someone hitting it: https://rachelbythebay.com/w/2011/06/07/forked/. You could google for more. That said, normally this isn't an issue in Python, because `multiprocessing` tries to reset the state of most mutexes when it forks as the result of creating a `multiprocessing.Process`. However, if you have mutexes that aren't reset after the `fork()` (and there are some C-level mutexes that fall into this category), you could still run into this issue. See http://bugs.python.org/issue6721 for more information. I can add a note referencing that bug to the README.
