### ISSUE TITLE
setup.py claims support for Python 3.3, but apparently not true

### ISSUE THREAD

**Issue by dg1727** [dano/aioprocessing#2]
setup.py says under `classifiers` that the `aioprocessing` module supports Python 3.3, but for example, \__init\__.py uses `multiprocessing.get_context()`
... and https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context says that `get_context()` is new in Python 3.4.  

An exception is generated on Python 3.3 because `get_context` is not in this Python version.  

Maybe eventually some code can be added to `aioprocessing` to avoid using `get_context()` if this method isn't available?  

Also, the code in Git is different than the code on PyPI, even though both say they are the same version, 0.0.1.  I substituted the Git rendition of the code into a Python 3.3 install, but it still failed with the same error.  

Hopefully the version# in Git can be incremented at some point.

**Comment by dano** [comment]
Right - Python 3.3 is only supported right now if you use the `asyncio` backport available on PyPI: https://pypi.python.org/pypi/asyncio. I'll investigate if the 3.3 version of `asyncio` can be easily supported when I get a chance. I'm not sure offhand how feasible it will be to only optionally support contexts, though. At the very least I'll clarify that you need the backported `asyncio` if you're using 3.3.

And you're right, I've made some changes to the github repo since I last published to PyPI, but I forgot to update the github version to reflect that. I'll fix that.

**Comment by dano** [comment]
I've added a note to the README stating you need Python 3.4+ or `asyncio` 3.4+ (which can be installed from PyPI). I'll leave this open for now in case I get around to looking at adding support for 3.3 without the PyPI `asyncio`.

**Comment by filmor** [comment]
This has nothing to do with asyncio, it is multiprocessing in Python 3.3 that is lacking. Any particular reason that you are using `get_context` here?

**Comment by dano** [comment]
@filmor You're right, the `asyncio` backport stuff doesn't fix `multiprocessing` issue, not sure what I was thinking above...

Anyway, `get_context` is used because a context is necessary to create many `multiprocessing` objects under Python 3.4+, and it's also possible to specify the context to use on a per-object basis, e.g.

ctx = multiprocessing.get_context('spawn')
p = AioProcess(..., context=ctx)
ctx2 = multiprocessing.get_context('fork')
p2 = AioProcess(..., context=ctx2)

I should be able to tweak things so that a default context isn't passed internally if running on Python 3.3, and so that the context kwarg is just ignored.

**Comment by dano** [comment]
Should be fixed now. Sorry for the delay.
